### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by IzzySoft** [Susheelkaram/Reeder#1]
I wonder what license you put your app under, as I couldn't find it mentioned. Could you please specify? Thanks in advance!

**Comment by IzzySoft** [comment]
Any chance, @Susheelkaram?

**Comment by Susheelkaram** [comment]
@IzzySoft Hey, I haven't added the licence details because of lack of time. Will add it soon.
May I know your concerned usecase, I may be able to help you better?

**Comment by IzzySoft** [comment]
Sure. Multiple reasons.

First, potential contributors (or "forkers") need to be safe; "no license" means "all rights reserved" and thus might bring them into trouble.

Second, my personal reason: https://apt.izzysoft.de/fdroid intended to include your app, to broaden your user base and make it easier to find, install and keep your app updated (updates are pulled automatically within 24h of your making them available – the index on the users' devices updates automatically, so update notifications will reach them or, with the F-Droid privileged extension, can even be applied automatically).

**Comment by IzzySoft** [comment]
So any chance? Are you still maintaining/developing the app?

**Comment by IzzySoft** [comment]
@Susheelkaram Still found no time? If you've already chosen a license, adding it shouldn't take too much time I'd say :wink:

**Comment by Susheelkaram** [comment]
@IzzySoft I have added the license. Thanks for reporting this.

**Comment by IzzySoft** [comment]
Thanks a lot, @Susheelkaram! Last question: with no release since 8/2021 and no recent commit to the app sources, are you still maintaining the app?

**Comment by Susheelkaram** [comment]
@IzzySoft I am not currently working on this because of time constraints but definitely planning to work on this in near future.
